const key='ebm.faculty.essentials.v1';let saved={},current=1,timer;
try{saved=JSON.parse(localStorage.getItem(key)||'{}');if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={}}catch{}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('show'),3500)}
async function copy(text){try{await navigator.clipboard.writeText(text);notice('已複製，請切換至 AI 工具貼上。')}catch{const t=document.getElementById('manualCopy');t.value=text;document.getElementById('copyDialog').showModal();t.focus();t.select()}}
function progress(){const n=COURSE.filter(e=>saved[e.id]).length;document.getElementById('progressText').textContent=n+' / '+COURSE.length;document.getElementById('progress').max=COURSE.length;document.getElementById('progress').value=n}
function route(id){if(!COURSE.some(e=>e.id===id))return;if(location.hash==='#lesson-'+id){render(true);return}location.hash='lesson-'+id}
function render(scroll=false){const e=COURSE.find(x=>x.id===current),index=COURSE.indexOf(e);document.getElementById('lessons').innerHTML=COURSE.map((x,i)=>`<button data-id="${x.id}" ${current===x.id?'aria-current="step"':''}><span class="num">${String(i+1).padStart(2,'0')}</span><span>${esc(x.title)}</span>${saved[x.id]?'<span class="done-mark" aria-label="已完成">✓</span>':''}</button>`).join('');
const tools=e.tool==='nblm'?'<a href="https://notebooklm.google.com/" target="_blank" rel="noopener noreferrer">開啟 NotebookLM ↗</a>':'<a href="https://gemini.google.com/" target="_blank" rel="noopener noreferrer">開啟 Gemini ↗</a><a href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">開啟 ChatGPT ↗</a>'+(e.tool==='image'?'':'<a href="https://claude.ai/" target="_blank" rel="noopener noreferrer">開啟 Claude ↗</a>');
const icebreakerTools=[1,10,11].includes(e.id)?'<a href="https://notebooklm.google.com/" target="_blank" rel="noopener noreferrer">開啟 NotebookLM ↗</a><a href="https://grok.com/" target="_blank" rel="noopener noreferrer">開啟 Grok ↗</a><a href="https://copilot.microsoft.com/" target="_blank" rel="noopener noreferrer">開啟 Copilot ↗</a>':'';
document.getElementById('lesson').innerHTML=`<div class="meta"><span>LAB ${String(index+1).padStart(2,'0')} / ${COURSE.length}</span><span>約 ${e.time} 分鐘</span></div><h2 id="lessonTitle">${esc(e.title)}</h2><p class="learning-point">${esc(e.point)}</p><div class="launch-links">${tools}${icebreakerTools}</div><ol class="steps">${e.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${e.id===7?'<div class="source-action"><button id="copySource">複製共用素材</button><span>先加入來源，再貼下方簡報指令。</span></div>':''}<div class="prompt"><div class="prompt-head"><label for="promptText">本題提示詞<small>${e.prompt.includes('【共用六頁素材】')?'複製時已包含六頁素材，不必另外貼。':'直接複製即可使用。'}</small></label><button id="copyPrompt">複製完整提示詞</button></div><textarea id="promptText" rows="10" readonly aria-label="本題提示詞">${esc(e.prompt.split('\n\n【共用六頁素材】')[0])}</textarea></div><div class="finish-target"><strong>完成到這裡</strong><p>${esc(e.done)}</p></div>${e.tip?`<p class="tip">${esc(e.tip)}</p>`:''}${e.id===8?'<p class="tip">圖片簡報的文字已成為圖片，後續較難編輯；先確認內容與中文字，再組合成簡報。</p>':''}<div class="lesson-bottom"><label class="finish"><input id="done" type="checkbox" ${saved[e.id]?'checked':''}>我已完成</label><div class="actions"><button id="prev" ${index===0?'disabled':''}>上一題</button><button id="next" ${index===COURSE.length-1?'disabled':''}>下一題 →</button></div></div>`;
document.getElementById('copyPrompt').onclick=()=>copy(e.prompt);const source=document.getElementById('copySource');if(source)source.onclick=()=>copy(MATERIAL);document.getElementById('done').onchange=ev=>{const wasComplete=COURSE.every(x=>saved[x.id]);saved[e.id]=ev.target.checked;try{localStorage.setItem(key,JSON.stringify(saved))}catch{notice('目前無法儲存，紀錄只保留在本次開啟期間。')}progress();const b=document.querySelector(`[data-id="${e.id}"]`);b.querySelector('.done-mark')?.remove();if(saved[e.id])b.insertAdjacentHTML('beforeend','<span class="done-mark" aria-label="已完成">✓</span>');if(!wasComplete&&COURSE.every(x=>saved[x.id]))celebrate()};document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>route(+b.dataset.id));document.getElementById('prev').onclick=()=>index>0&&route(COURSE[index-1].id);document.getElementById('next').onclick=()=>index<COURSE.length-1&&route(COURSE[index+1].id);progress();if(scroll){document.getElementById('lesson').scrollIntoView({block:'start'});document.getElementById('lesson').focus({preventScroll:true})}}
function fromHash(scroll){const m=location.hash.match(/^#lesson-(\d+)$/);current=m&&COURSE.some(e=>e.id===+m[1])?+m[1]:1;render(scroll)}window.addEventListener('hashchange',()=>fromHash(true));document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>copy(MATERIAL));document.getElementById('sourceText').textContent=MATERIAL;document.getElementById('selectCopy').onclick=()=>{const t=document.getElementById('manualCopy');t.focus();t.select()};document.getElementById('closeCopy').onclick=()=>document.getElementById('copyDialog').close();fromHash(false);

function celebrate(){
 const dialog=document.getElementById('completionDialog');
 document.getElementById('completionMessage').textContent=`${COURSE.length}／${COURSE.length} 題全數完成！你已走過文字、圖像、簡報到互動網頁的創作旅程。`;
 dialog.querySelector('.celebration-particles').innerHTML=Array.from({length:24},(_,i)=>`<i style="--x:${(i*37)%100}%;--delay:${(i%6)*0.12}s;--turn:${i%2?180:-180}deg;--color:${['#67e8cd','#8bb7fa','#f4d58a'][i%3]}"></i>`).join('');
 dialog.showModal();
}
const completionDialog=document.getElementById('completionDialog');
document.getElementById('closeCompletion').onclick=()=>completionDialog.close();
completionDialog.addEventListener('close',()=>{completionDialog.querySelector('.celebration-particles').replaceChildren();document.getElementById('done')?.focus({preventScroll:true})});
